# Generated by Django 2.2.6 on 2019-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cabinetcase_coolingsystem_graphicscard_headphone_laptop_memory_monitor_motherboard_powersupply_proce'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabinetcase',
            table='cabinetcase',
        ),
    ]
